file_format: "1"
id: tg73
name: TG73
type: shield
url: 
requires:
  - zmk,kscan-gpio-matrix
  - zmk,matrix-transform
supported_boards:
  - nrfmicro_13
  - nrfmicro_13_flipped
features:
  - keys
  - underglow
  - display
